name: defreeze_shoulder
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+5

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dropdown_button2: ^2.3.9
  http: ^1.2.2
  font_awesome_flutter: ^10.3.0
  image_picker: ^0.8.5+3
  flutter_vector_icons: ^2.0.0
  shared_preferences: ^2.0.0
  table_calendar: ^3.0.0
  dio: ^5.0.0
  provider: ^6.0.0
  pie_chart: ^5.0.0
  fl_chart: ^0.40.0
  syncfusion_flutter_charts: ^20.1.55
  charts_flutter: ^0.12.0
  intl: ^0.17.0
  url_launcher: ^6.0.9
  video_player: ^2.4.6
  video_player_platform_interface: ^6.0.0
  chewie: ^1.3.1
  animate_do: ^2.0.0
  flutter_screenutil: ^5.0.0
  auto_size_text: ^3.0.0  # Check for the latest version
  permission_handler: ^10.0.0
  file_picker: ^5.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo2.png
    - assets/medical.png
    - assets/crowd.png
    - assets/1.jpeg
    - assets/2.jpeg
    - assets/3.jpeg
    - assets/1.jpg
    - assets/2.jpg
    - assets/3.jpg
    - assets/IMG_8264 1.png
    - assets/IMG_8264 3.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo21.png"
